### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by renesass** [automl-classroom/iML-ws21-ex02#1]
* Updated tests/plotting
* Added  requirements

**Comment by dwoiwode** [comment]
It would be nice if files with tests inside are prefixed by `test_`, to enable [autodisovery of tests](https://docs.pytest.org/en/6.2.x/goodpractices.html#test-discovery) by pytest. With this naming convention it is possible to run `pytest tests` to execute all tests at once.

e.g.
```
tests/
| - __init__.py
| - config.py
| - test_decision_trees.py
| - test_linear_models.py
| - test_plotting.py
```

**Comment by dwoiwode** [comment]
Also, for the next exercises, I think it would be easier to read if you create a pull request instead of an issue so we can see the actual changes to the code without having to search through the commits since date X.

**Comment by renesass** [comment]
Thank you for your feedback. These changes will be applied to the next exericses. :)
