### ISSUE TITLE
Push without triggering the Pipeline

### ISSUE THREAD

**Issue by felixmeyjr** [automl-classroom/iML-ws21-ex02#3]
Hi, is it possible to push without triggering the pipeline? I know that this is possible with Gitlab with something like push -o ci.skip, but googling didnt show up any good results.

When working within a team, we obviously push a lot without the code being correct and ready.
Thanks

**Comment by renesass** [comment]
I'm not aware of such a command. However, just push as much as you please. It doesn't matter if the tests fail.
