### ISSUE TITLE
Formula on exercise 2

### ISSUE THREAD

**Issue by hiepb** [automl-classroom/iML-ws21-ex02#5]
There might be a typo thats unclear or not defined...
On the exercise 2.2: Custom Linear Regression
Its not clear, what the sum formula is to calculate the deviate of L to b
<img width="103" alt="Bildschirmfoto 2021-10-22 um 19 53 05" src="https://user-images.githubusercontent.com/83126156/138500884-4dd5e451-7971-4aed-a078-a3c826d545ca.png">

**Comment by maxidl** [comment]
Hi,
when computing the loss on the examples in X, you should get a 1d vector containing one loss value per example. The sum here indicates to reduce them to a scalar value via a sum over this 1d vector.
